-- =================================================================
-- 1. SCHOLARSHIPS TABLE & POLICIES
-- =================================================================
CREATE TABLE IF NOT EXISTS public.scholarships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  provider TEXT NOT NULL,
  description TEXT,
  amount TEXT NOT NULL,
  deadline DATE,
  education_levels TEXT[] DEFAULT '{}',
  courses TEXT[] DEFAULT '{}',
  minimum_percentage NUMERIC,
  maximum_income NUMERIC,
  eligible_gender TEXT DEFAULT 'Any',
  eligible_categories TEXT[] DEFAULT '{}',
  eligible_states TEXT[] DEFAULT '{}',
  required_documents TEXT[] DEFAULT '{}',
  application_url TEXT NOT NULL,
  source_url TEXT NOT NULL,
  source_name TEXT NOT NULL,
  is_verified BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security (read-only for all authenticated students)
ALTER TABLE public.scholarships ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone authenticated can view scholarships" ON public.scholarships;
CREATE POLICY "Anyone authenticated can view scholarships"
  ON public.scholarships FOR SELECT
  TO authenticated
  USING (true);

-- =================================================================
-- 2. SEED OFFICIAL REAL-WORLD INDIAN SCHOLARSHIPS
-- =================================================================
INSERT INTO public.scholarships (
  title,
  provider,
  description,
  amount,
  deadline,
  education_levels,
  courses,
  minimum_percentage,
  maximum_income,
  eligible_gender,
  eligible_categories,
  eligible_states,
  required_documents,
  application_url,
  source_url,
  source_name,
  is_verified
) VALUES 
(
  'Central Sector Scheme of Scholarships for College and University Students',
  'Ministry of Education, Govt. of India',
  'Provides financial assistance to meritorious students from low-income families pursuing regular degree and professional courses in recognized colleges/universities.',
  '₹20,000 per annum',
  '2026-10-31',
  ARRAY['Undergraduate', 'B.Tech', 'Degree', 'Class 12 Passed'],
  ARRAY['Engineering', 'Medical', 'Science', 'Commerce', 'Arts', 'All'],
  80.0,
  450000,
  'Any',
  ARRAY['General', 'OBC', 'SC', 'ST', 'EWS', 'All'],
  ARRAY['All India'],
  ARRAY['Marksheet', 'Income Certificate', 'Aadhaar Card', 'College Admission Proof'],
  'https://scholarships.gov.in',
  'https://scholarships.gov.in',
  'National Scholarship Portal (scholarships.gov.in)',
  true
),
(
  'AICTE Pragati Scholarship Scheme for Girl Students',
  'All India Council for Technical Education (AICTE)',
  'Aiming to empower girls and promote technical education by providing scholarships for girl students admitted to AICTE approved technical degree courses.',
  '₹50,000 per annum',
  '2026-11-15',
  ARRAY['Undergraduate', 'B.Tech', 'Engineering', 'Diploma'],
  ARRAY['Engineering', 'Technology', 'Architecture', 'Pharmacy'],
  60.0,
  800000,
  'Female',
  ARRAY['General', 'OBC', 'SC', 'ST', 'EWS', 'All'],
  ARRAY['All India'],
  ARRAY['Marksheet', 'Income Certificate', 'Aadhaar Card', 'Admission Letter', 'College ID'],
  'https://scholarships.gov.in',
  'https://www.aicte-india.org/schemes/students-development-schemes/pragati',
  'AICTE Official Portal',
  true
),
(
  'Post-Matric Scholarship for SC/ST/OBC Students',
  'Ministry of Social Justice and Empowerment / Ministry of Tribal Affairs',
  'Government financial assistance supporting post-secondary education for reserved category students to pursue higher studies.',
  'Full Tuition Fee + Maintenance Allowance up to ₹1,200/month',
  '2026-11-30',
  ARRAY['Undergraduate', 'Postgraduate', 'Class 11', 'Class 12', 'B.Tech', 'Degree'],
  ARRAY['All'],
  50.0,
  250000,
  'Any',
  ARRAY['SC', 'ST', 'OBC'],
  ARRAY['All India'],
  ARRAY['Marksheet', 'Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'Fee Receipt'],
  'https://scholarships.gov.in',
  'https://socialjustice.gov.in',
  'Ministry of Social Justice & Empowerment',
  true
),
(
  'UP Post Matric Scholarship & Fee Reimbursement Scheme',
  'Social Welfare Department, Govt. of Uttar Pradesh',
  'Financial assistance and tuition fee reimbursement for domicile students of Uttar Pradesh pursuing graduation or professional degrees.',
  'Up to ₹50,000 Fee Reimbursement + Allowance',
  '2026-10-15',
  ARRAY['Undergraduate', 'Postgraduate', 'B.Tech', 'Diploma', 'Class 12 Passed'],
  ARRAY['Engineering', 'Medical', 'Science', 'Management', 'Arts'],
  55.0,
  200000,
  'Any',
  ARRAY['General', 'OBC', 'SC', 'ST', 'EWS', 'All'],
  ARRAY['Uttar Pradesh'],
  ARRAY['Marksheet', 'Income Certificate', 'Caste Certificate', 'Domicile Certificate', 'Aadhaar Card', 'Fee Receipt'],
  'https://scholarship.up.gov.in',
  'https://scholarship.up.gov.in',
  'UP Scholarship Official Portal',
  true
),
(
  'Reliance Foundation Undergraduate Scholarships',
  'Reliance Foundation',
  'Merit-cum-means scholarship supporting undergraduate students across all disciplines to help them pursue higher education without financial constraints.',
  'Up to ₹2,00,000 over course duration',
  '2026-10-06',
  ARRAY['Undergraduate', 'B.Tech', 'B.Sc', 'B.Com', 'B.A'],
  ARRAY['All Streams'],
  60.0,
  1500000,
  'Any',
  ARRAY['General', 'OBC', 'SC', 'ST', 'EWS', 'All'],
  ARRAY['All India'],
  ARRAY['Marksheet', 'Income Certificate', 'Aadhaar Card', 'Bonafide Certificate'],
  'https://www.scholarships.reliancefoundation.org',
  'https://www.scholarships.reliancefoundation.org',
  'Reliance Foundation Official',
  true
),
(
  'ONGC Scholarship for Meritorious SC/ST/OBC/EWS Students',
  'Oil and Natural Gas Corporation (ONGC) Foundation',
  'Scholarship grant for economically weaker and marginalized students pursuing 1st year Engineering, MBBS, MBA, or Master in Geophysics/Geology.',
  '₹48,000 per annum',
  '2026-12-15',
  ARRAY['Undergraduate', 'B.Tech', 'MBBS', 'Postgraduate', 'MBA'],
  ARRAY['Engineering', 'Medical', 'Management', 'Geology'],
  60.0,
  200000,
  'Any',
  ARRAY['SC', 'ST', 'OBC', 'EWS'],
  ARRAY['All India'],
  ARRAY['Marksheet', 'Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'College ID'],
  'https://ongcscholar.org',
  'https://ongcscholar.org',
  'ONGC Foundation Official',
  true
),
(
  'Kotak Kanya Scholarship',
  'Kotak Education Foundation',
  'Financial support to meritorious girl students from underprivileged families who have secured admission to professional graduation courses in top institutes.',
  'Up to ₹1,50,000 per year',
  '2026-09-30',
  ARRAY['Undergraduate', 'B.Tech', 'MBBS', 'B.Arch', 'Professional Courses'],
  ARRAY['Engineering', 'Medical', 'Architecture', 'Law'],
  75.0,
  600000,
  'Female',
  ARRAY['General', 'OBC', 'SC', 'ST', 'EWS', 'All'],
  ARRAY['All India'],
  ARRAY['Marksheet', 'Income Certificate', 'Aadhaar Card', 'College Admission Proof', 'Fee Structure'],
  'https://kotakeducation.org/kotak-kanya-scholarship',
  'https://kotakeducation.org',
  'Kotak Education Foundation',
  true
),
(
  'Prime Minister''s Scholarship Scheme (PMSS) for Wards of Ex-Servicemen & CAPF',
  'Welfare and Rehabilitation Board (WARB), Ministry of Home Affairs',
  'Scholarship program to encourage technical and post-graduate education for dependent wards and widows of Central Armed Police Forces & Ex-servicemen.',
  '₹3,000/month for girls, ₹2,500/month for boys',
  '2026-11-30',
  ARRAY['Undergraduate', 'B.Tech', 'MBBS', 'BCA', 'B.Pharm', 'Degree'],
  ARRAY['Engineering', 'Medical', 'Dental', 'Veterinary', 'Pharmacy', 'Management'],
  60.0,
  null,
  'Any',
  ARRAY['General', 'OBC', 'SC', 'ST', 'EWS', 'All'],
  ARRAY['All India'],
  ARRAY['Marksheet', 'Service/Discharge Certificate', 'Aadhaar Card', 'College Bonafide'],
  'https://scholarships.gov.in',
  'https://www.ksb.gov.in',
  'Kendriya Sainik Board (KSB)',
  true
)
ON CONFLICT DO NOTHING;
