import { Opportunity } from "./types";

export const UNIFIED_OPPORTUNITIES_CATALOG: Opportunity[] = [
  // =========================================================================
  // SCHOLARSHIPS
  // =========================================================================
  {
    id: "opp-cs-scheme",
    type: "scholarship",
    title: "Central Sector Scheme of Scholarships for College and University Students",
    organization: "Ministry of Education, Govt. of India",
    description: "Financial assistance to meritorious students from low-income families pursuing regular degree and professional courses in recognized colleges/universities.",
    amount: "₹20,000 per annum",
    deadline: "2026-10-31",
    location: "All India",
    remote: false,
    duration: "Annual",
    eligibility_text: "Applicants must have passed Class 12 with at least 80% marks, annual family income below ₹4,50,000, and pursuing full-time undergraduate or professional degree courses.",
    requirements: [
      {
        field: "class_12_percentage",
        operator: ">=",
        value: 80.0,
        required: true,
        label: "Class 12 Percentage",
        description: "Minimum 80% in Class 12 / Higher Secondary",
      },
      {
        field: "family_income",
        operator: "<=",
        value: 450000,
        required: true,
        label: "Annual Family Income",
        description: "Family income must not exceed ₹4,50,000/year",
      },
    ],
    required_skills: [],
    preferred_skills: [],
    education_requirements: ["Undergraduate", "B.Tech", "Degree", "Class 12 Passed"],
    required_documents: ["Class 12 Marksheet", "Income Certificate", "Aadhaar Card", "Admission Proof"],
    application_url: "https://scholarships.gov.in",
    source_url: "https://scholarships.gov.in",
    application_status: "open",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-25T00:00:00Z",
  },
  {
    id: "opp-aicte-pragati",
    type: "scholarship",
    title: "AICTE Pragati Scholarship Scheme for Girl Students",
    organization: "All India Council for Technical Education (AICTE)",
    description: "Empowers female students to pursue technical education by providing scholarships for AICTE-approved degree and diploma courses.",
    amount: "₹50,000 per annum",
    deadline: "2026-11-15",
    location: "All India",
    remote: false,
    duration: "Full Course Duration",
    eligibility_text: "Female students admitted to first year degree/diploma technical courses in AICTE approved institutions with family income less than ₹8,00,000 and minimum 60% in Class 12.",
    requirements: [
      {
        field: "gender",
        operator: "==",
        value: "Female",
        required: true,
        label: "Gender Restriction",
        description: "Exclusively for Female students",
      },
      {
        field: "class_12_percentage",
        operator: ">=",
        value: 60.0,
        required: true,
        label: "Class 12 Percentage",
        description: "Minimum 60% in Class 12",
      },
      {
        field: "family_income",
        operator: "<=",
        value: 800000,
        required: true,
        label: "Annual Family Income",
        description: "Family income must not exceed ₹8,00,000/year",
      },
    ],
    required_skills: [],
    preferred_skills: [],
    education_requirements: ["Undergraduate", "B.Tech", "Engineering", "Diploma"],
    required_documents: ["Class 12 Marksheet", "Income Certificate", "Aadhaar Card", "Admission Letter"],
    application_url: "https://scholarships.gov.in",
    source_url: "https://www.aicte-india.org/schemes/students-development-schemes/pragati",
    application_status: "open",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-25T00:00:00Z",
  },
  {
    id: "opp-reliance-foundation",
    type: "scholarship",
    title: "Reliance Foundation Undergraduate Scholarship",
    organization: "Reliance Foundation",
    description: "Merit-cum-means scholarship supporting undergraduate students across all disciplines to help them pursue higher education without financial constraints.",
    amount: "Up to ₹2,00,000 over course duration",
    deadline: "2026-10-06",
    location: "All India",
    remote: false,
    duration: "Up to 4 Years",
    eligibility_text: "Indian resident students enrolled in first year undergraduate degree courses with minimum 60% in Class 12 and household income less than ₹15,00,000 (preference under ₹2.5 Lakh).",
    requirements: [
      {
        field: "class_12_percentage",
        operator: ">=",
        value: 60.0,
        required: true,
        label: "Class 12 Percentage",
        description: "Minimum 60% in Class 12",
      },
      {
        field: "family_income",
        operator: "<=",
        value: 1500000,
        required: true,
        label: "Household Income",
        description: "Annual family income up to ₹15,00,000",
      },
    ],
    required_skills: [],
    preferred_skills: [],
    education_requirements: ["Undergraduate", "B.Tech", "B.Sc", "B.Com", "BA", "First Year"],
    required_documents: ["Class 12 Marksheet", "Income Proof", "Aadhaar Card", "College Bonafide"],
    application_url: "https://www.reliancefoundation.org/scholarships",
    source_url: "https://www.reliancefoundation.org",
    application_status: "closing_soon",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-25T00:00:00Z",
  },
  {
    id: "opp-up-post-matric",
    type: "scholarship",
    title: "UP Post Matric Scholarship & Fee Reimbursement",
    organization: "Social Welfare Department, Govt. of Uttar Pradesh",
    description: "Financial assistance and tuition fee reimbursement for domicile students of Uttar Pradesh pursuing graduation or professional degrees.",
    amount: "Up to ₹50,000 Fee Reimbursement",
    deadline: "2026-10-15",
    location: "Uttar Pradesh",
    remote: false,
    duration: "Academic Year",
    eligibility_text: "Permanent residents of Uttar Pradesh studying in recognized colleges with family income under ₹2,00,000/year and minimum 50% in qualifying exam.",
    requirements: [
      {
        field: "domicile",
        operator: "==",
        value: "Uttar Pradesh",
        required: true,
        label: "State of Domicile",
        description: "Permanent resident of Uttar Pradesh",
      },
      {
        field: "family_income",
        operator: "<=",
        value: 200000,
        required: true,
        label: "Annual Family Income",
        description: "Family income must not exceed ₹2,00,000/year",
      },
    ],
    required_skills: [],
    preferred_skills: [],
    education_requirements: ["Undergraduate", "Postgraduate", "B.Tech", "Diploma"],
    required_documents: ["Domicile Certificate", "Income Certificate", "Caste Certificate", "Marksheet", "Aadhaar Card"],
    application_url: "https://scholarship.up.gov.in",
    source_url: "https://scholarship.up.gov.in",
    application_status: "open",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-25T00:00:00Z",
  },

  // =========================================================================
  // INTERNSHIPS
  // =========================================================================
  {
    id: "opp-google-step",
    type: "internship",
    title: "Google Student Training in Engineering Program (STEP) Internship 2026",
    organization: "Google India",
    description: "Development internship program designed for undergraduate students with a passion for computer science and technology. Includes technical training and project mentorship.",
    stipend: "₹85,000 / month + Relocation & Housing",
    deadline: "2026-09-30",
    location: "Bengaluru / Hyderabad",
    remote: false,
    duration: "10-12 Weeks (Summer 2026)",
    eligibility_text: "Second-year undergraduate students pursuing B.Tech/B.E. in Computer Science or related fields with minimum 7.5 CGPA (or 75% in 12th) and strong programming skills in C++, Java, or Python.",
    requirements: [
      {
        field: "branch",
        operator: "contains",
        value: ["computer science", "information technology", "electronics", "data science"],
        required: true,
        label: "Degree Branch",
        description: "Enrolled in Computer Science, IT, Electronics or related engineering disciplines",
      },
      {
        field: "class_12_percentage",
        operator: ">=",
        value: 75.0,
        required: true,
        label: "Class 12 Percentage",
        description: "Minimum 75% in Class 12 / Higher Secondary",
      },
    ],
    required_skills: ["Python", "Data Structures", "Algorithms", "Git"],
    preferred_skills: ["C++", "Java", "Web Development"],
    education_requirements: ["B.Tech", "B.E.", "Undergraduate", "2nd Year"],
    required_documents: ["Resume", "College ID", "Class 12 Marksheet"],
    application_url: "https://careers.google.com/students",
    source_url: "https://careers.google.com/jobs/results/?q=STEP",
    application_status: "closing_soon",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-25T00:00:00Z",
  },
  {
    id: "opp-microsoft-engage",
    type: "internship",
    title: "Microsoft Software Engineering Internship",
    organization: "Microsoft India",
    description: "Software engineering internship working on core Microsoft cloud products, AI services, and developer platforms alongside senior engineering mentors.",
    stipend: "₹1,25,000 / month + Benefits",
    deadline: "2026-10-15",
    location: "Hyderabad / Noida / Bengaluru",
    remote: false,
    duration: "8-12 Weeks",
    eligibility_text: "Pre-final and final year B.Tech/B.E./Dual Degree students with minimum 7.0 CGPA and solid proficiency in object-oriented programming, data structures, and algorithms.",
    requirements: [
      {
        field: "cgpa",
        operator: ">=",
        value: 7.0,
        required: true,
        label: "Minimum CGPA",
        description: "Minimum 7.0 CGPA throughout graduation",
      },
      {
        field: "branch",
        operator: "contains",
        value: ["computer science", "information technology", "electronics", "electrical"],
        required: true,
        label: "Branch of Study",
        description: "Computer Science, IT, Electronics or Electrical Engineering",
      },
    ],
    required_skills: ["Data Structures", "Algorithms", "C++", "Java", "Git"],
    preferred_skills: ["React", "TypeScript", "Cloud Computing", "SQL"],
    education_requirements: ["B.Tech", "B.E.", "M.Tech", "MCA"],
    required_documents: ["Resume", "Latest Semester Marksheet", "College ID"],
    application_url: "https://careers.microsoft.com/students",
    source_url: "https://careers.microsoft.com",
    application_status: "open",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-25T00:00:00Z",
  },
  {
    id: "opp-isro-research",
    type: "internship",
    title: "ISRO Student Internship & Research Program",
    organization: "Indian Space Research Organisation (ISRO)",
    description: "Hands-on engineering internship in satellite communications, avionics, payload data processing, and space robotics across ISRO research centres.",
    stipend: "₹15,000 / month + Lab Access",
    deadline: "2026-11-01",
    location: "Bengaluru / Ahmedabad / Thiruvananthapuram",
    remote: false,
    duration: "45-90 Days",
    eligibility_text: "Indian citizens pursuing B.Tech/B.E. in Aerospace, Mechanical, ECE, or Computer Science with minimum 80% in 12th and 7.5 CGPA in graduation.",
    requirements: [
      {
        field: "nationality",
        operator: "==",
        value: "Indian",
        required: true,
        label: "Citizenship",
        description: "Indian Citizens only",
      },
      {
        field: "class_12_percentage",
        operator: ">=",
        value: 80.0,
        required: true,
        label: "Class 12 Percentage",
        description: "Minimum 80% in Class 12 / Higher Secondary",
      },
      {
        field: "cgpa",
        operator: ">=",
        value: 7.5,
        required: true,
        label: "Minimum CGPA",
        description: "Minimum 7.5 CGPA",
      },
    ],
    required_skills: ["Python", "C++", "Signal Processing", "Data Structures"],
    preferred_skills: ["MATLAB", "Linux", "Robotics"],
    education_requirements: ["B.Tech", "B.E.", "M.Tech", "Pre-Final Year"],
    required_documents: ["College NOC / Recommendation", "Marksheets", "Aadhaar Card"],
    application_url: "https://www.isro.gov.in/Internships.html",
    source_url: "https://www.isro.gov.in",
    application_status: "open",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-25T00:00:00Z",
  },
  {
    id: "opp-tcs-enquode",
    type: "internship",
    title: "TCS Research & Digital Innovation Internship",
    organization: "Tata Consultancy Services (TCS)",
    description: "Industrial research internship in applied AI, cybersecurity, high-performance computing, and distributed architectures for tech undergraduates.",
    stipend: "₹35,000 / month",
    deadline: "2026-10-20",
    location: "Pune / Mumbai / Bengaluru / Remote",
    remote: true,
    duration: "8-16 Weeks",
    eligibility_text: "Enrolled in B.Tech/B.E./M.Sc/MCA with minimum 65% aggregate score in 10th, 12th, and graduation with no active backlogs.",
    requirements: [
      {
        field: "class_10_percentage",
        operator: ">=",
        value: 65.0,
        required: true,
        label: "Class 10 Percentage",
        description: "Minimum 65% in Class 10",
      },
      {
        field: "class_12_percentage",
        operator: ">=",
        value: 65.0,
        required: true,
        label: "Class 12 Percentage",
        description: "Minimum 65% in Class 12",
      },
    ],
    required_skills: ["Python", "Java", "SQL", "Git"],
    preferred_skills: ["Machine Learning", "Docker", "REST APIs"],
    education_requirements: ["B.Tech", "B.E.", "MCA", "M.Tech"],
    required_documents: ["Resume", "10th Marksheet", "12th Marksheet", "College ID"],
    application_url: "https://www.tcs.com/careers/entry-level",
    source_url: "https://www.tcs.com",
    application_status: "open",
    created_at: "2026-08-01T00:00:00Z",
    updated_at: "2026-08-25T00:00:00Z",
  },
];
